class databaseQueryHandler:
    insertChapter="INSERT INTO `test_maker`.`chapter` (`chap_name`, `subject_id`, `chapter_number`) VALUES (%s,%s,%s);"
    insertQuestion="INSERT INTO `test_maker`.`question` (`question_desc`, `chapter_id`, `question_type`) VALUES (%s,%s,%s);"
    insertMcqs="INSERT INTO `test_maker`.`mcqs` (`mcq_desc`, `option1`, `option2`, `option3`, `option4`, `chapter_id`) VALUES (%s,%s,%s,%s,%s,%s);"
    insertTranslation=""
    insertTest=""
    insertSubject="INSERT INTO `test_maker`.`subject` (`subject_name`, `class_id`) VALUES (%s,%s);"
    insertSubjectQuestionTypes="INSERT INTO `test_maker`.`subject_type` (`subject_id`, `type_id`) VALUES (%s,%s);"
    insertClass="""INSERT INTO `test_maker`.`class` (`class_name`) VALUES (%s);"""
    insertLanguage=""
    insertUser="""INSERT INTO `test_maker`.`user` (`user_name`, `password`, `institute_name`, `institute_Address`, `is_allowed_to_make_changes`) VALUES (%s,%s,%s,%s,%s);"""

    fetchUsers="SELECT * FROM `test_maker`.`user`;"
    fetchClasses="SELECT * FROM `test_maker`.`class`;"
    fetchQuestionTypes="select * from `test_maker`.`question_type`"
    fetchSubjectQuestionTypes="select stype.type_id,type.type_name from subject_Type as stype join question_type as type where stype.subject_id= %s and stype.type_id=type.type_id;"
    fetchSubjects="SELECT * FROM `test_maker`.`subject` WHERE `class_id`=%s;"
    fetchChapters = "SELECT * FROM `test_maker`.`chapter` WHERE `subject_id`=%s;"
    fetchQuestions="SELECT * FROM `test_maker`.`question` WHERE `chapter_id` IN (placeholders) and `question_type`=%s;"
    updateQuestion = ""
    updateTranslation = ""
    updateTest = ""
    updateSubject = ""
    updateClass = ""
    updateLanguage=""

